linux:
  imageName: fluent/fluent-bit
  imageTag: 1.7.4
  nodeSelector:
    kubernetes.io/os: linux
  tolerations:
    - effect: NoSchedule
      operator: Exists
    - key: CriticalAddonsOnly
      operator: Exists

hasDocker: false
namespaces: []
#- name: ns1
#  accountName: key1
#  accountKey: aaa
#- name: ns2
#  accountName: key2
#  accountKey: bbb
