apiVersion: v1
kind: Secret
metadata:
  name: logging
type: Opaque
data:
  {{- range $namespace := .Values.namespaces }}
  {{- upper .name | replace "-" "_"}}_ACCOUNT_NAME: {{ $namespace.accountName | b64enc  }}
  {{- upper .name | replace "-" "_"}}_ACCOUNT_KEY: {{ $namespace.accountKey | b64enc  }}
  {{- end }}