apiVersion: v1
kind: Secret
metadata:
  name: logging
type: Opaque
data:
  {{- range $namespace := .Values.namespaces }}
  LAW_{{- upper .name | replace "-" "_"}}_ID: {{ $namespace.lawId | b64enc  }}
  LAW_{{- upper .name | replace "-" "_"}}_KEY: {{ $namespace.lawKey | b64enc  }}
  {{- end }}